apiVersion: v1
kind: PersistentVolume
metadata:
  name: mvn
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mvn"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
