apiVersion: v1
kind: PersistentVolume
metadata:
  name: scf
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/scf"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
