apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: argocd.webapp-coreapp.p16n.org
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80
