---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  sourceRepos:
  - 'git@github.com:tafy2392/cluster-infra-webapp.git'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
