apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-webapp
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: apps/webapp
    repoURL: git@github.com:tafy2392/cluster-infra-webapp.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
